import PDFDocument from 'pdfkit';
import prisma from '../../config/database';
import { AppError } from '../../middleware/errorHandler';
import { storageService } from '../storage/storage.service';

/**
 * Pay Statement PDF Service.
 * Generates Section 17-compliant pay statements showing gross, deductions, net.
 * Documents retained for 7 years per data retention policy.
 */
export class PayStatementService {
  /**
   * Generate a pay statement PDF for a completed payment.
   * Returns a Buffer containing the PDF.
   */
  async generatePayStatement(paymentId: string): Promise<Buffer> {
    const payment = await prisma.payment.findUnique({
      where: { id: paymentId },
      include: {
        shift: {
          include: {
            employer: { select: { businessName: true, kraPin: true } },
          },
        },
        worker: {
          select: { firstName: true, lastName: true },
        },
      },
    });

    if (!payment) throw new AppError(404, 'Payment not found');

    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({ size: 'A4', margin: 50 });

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text('klokd', { align: 'left' });
      doc.fontSize(8).font('Helvetica').fillColor('#6B7280')
        .text('klokd.co.ke · Kirimon Market Ventures', { align: 'left' });
      doc.moveDown(0.5);

      doc.fontSize(14).font('Helvetica-Bold').fillColor('#0A0A0F')
        .text('Pay Statement', { align: 'left' });
      doc.moveDown(0.3);

      // Reference
      doc.fontSize(9).font('Helvetica').fillColor('#6B7280')
        .text(`Reference: ${payment.id}`);
      doc.text(`Date: ${payment.paidAt?.toISOString().split('T')[0] || 'Pending'}`);
      doc.text(`M-Pesa Ref: ${payment.mpesaRef || payment.darajaRef || 'N/A'}`);
      doc.moveDown(1);

      // Worker & Employer info
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0A0A0F')
        .text('Worker');
      doc.fontSize(9).font('Helvetica').fillColor('#6B7280')
        .text(`${payment.worker.firstName} ${payment.worker.lastName}`);
      doc.moveDown(0.5);

      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0A0A0F')
        .text('Employer');
      doc.fontSize(9).font('Helvetica').fillColor('#6B7280')
        .text(payment.shift.employer.businessName);
      if (payment.shift.employer.kraPin) {
        doc.text(`KRA PIN: ${payment.shift.employer.kraPin}`);
      }
      doc.moveDown(1);

      // Shift details
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0A0A0F')
        .text('Shift Details');
      doc.fontSize(9).font('Helvetica').fillColor('#6B7280');
      doc.text(`Role: ${payment.shift.role}`);
      doc.text(`Date: ${payment.shift.date.toISOString().split('T')[0]}`);
      doc.text(`Location: ${payment.shift.locationName || 'N/A'}`);
      doc.moveDown(1);

      // Earnings table
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0A0A0F')
        .text('Earnings & Deductions');
      doc.moveDown(0.3);

      const drawRow = (label: string, amount: number, bold = false, color = '#0A0A0F') => {
        const y = doc.y;
        doc.fontSize(9).font(bold ? 'Helvetica-Bold' : 'Helvetica').fillColor(color);
        doc.text(label, 50, y, { width: 300 });
        doc.text(`KES ${amount.toLocaleString()}`, 350, y, { width: 150, align: 'right' });
        doc.moveDown(0.3);
      };

      drawRow('Gross Earnings', payment.grossKes, true);

      // Line
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E8EDE8').stroke();
      doc.moveDown(0.3);

      doc.fontSize(9).font('Helvetica-Bold').fillColor('#6B7280').text('Statutory Deductions');
      doc.moveDown(0.2);
      drawRow('  PAYE', payment.payeKes, false, '#6B7280');
      drawRow('  NSSF Tier I', payment.nssfTier1Kes, false, '#6B7280');
      drawRow('  NSSF Tier II', payment.nssfTier2Kes, false, '#6B7280');
      drawRow('  SHIF', payment.shifKes, false, '#6B7280');
      if (payment.ahlKes > 0) drawRow('  AHL', payment.ahlKes, false, '#6B7280');

      // Line
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#E8EDE8').stroke();
      doc.moveDown(0.3);

      drawRow('Net Pay (to M-Pesa)', payment.netKes, true, '#00A870');

      doc.moveDown(1);

      // Footer
      doc.fontSize(7).font('Helvetica').fillColor('#6B7280')
        .text('This pay statement is generated by Klokd on behalf of the employer. ', { continued: true })
        .text('Retained for 7 years per Kenya Employment Act requirements.');
      doc.text(`Retain until: ${payment.retainUntil.toISOString().split('T')[0]}`);

      doc.end();
    });
  }

  /**
   * Generate pay statement PDF and store in Supabase Storage.
   * Returns the storage key for retrieval.
   */
  async generateAndStore(paymentId: string): Promise<string> {
    const pdfBuffer = await this.generatePayStatement(paymentId);
    const storageKey = await storageService.uploadPayStatement(paymentId, pdfBuffer);
    return storageKey;
  }

  /**
   * Generate a monthly pay summary for a worker.
   */
  async getMonthlyStatement(workerId: string, year: number, month: number) {
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    const payments = await prisma.payment.findMany({
      where: {
        workerId,
        status: 'COMPLETED',
        paidAt: { gte: startDate, lte: endDate },
      },
      include: {
        shift: { select: { role: true, date: true, locationName: true } },
      },
      orderBy: { paidAt: 'asc' },
    });

    const totals = payments.reduce((acc, p) => ({
      grossKes: acc.grossKes + p.grossKes,
      payeKes: acc.payeKes + p.payeKes,
      nssfKes: acc.nssfKes + p.nssfTier1Kes + p.nssfTier2Kes,
      shifKes: acc.shifKes + p.shifKes,
      ahlKes: acc.ahlKes + p.ahlKes,
      netKes: acc.netKes + p.netKes,
    }), { grossKes: 0, payeKes: 0, nssfKes: 0, shifKes: 0, ahlKes: 0, netKes: 0 });

    return {
      period: `${year}-${String(month).padStart(2, '0')}`,
      shiftCount: payments.length,
      payments: payments.map(p => ({
        id: p.id,
        date: p.paidAt,
        role: p.shift.role,
        location: p.shift.locationName,
        grossKes: p.grossKes,
        netKes: p.netKes,
        mpesaRef: p.mpesaRef ?? p.darajaRef,
      })),
      totals,
    };
  }
}

export const payStatementService = new PayStatementService();
